config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'recipes#index'
  get '/user/profile' => 'users#show'

  resources :recipes do
    resources :comments
  end

  resources :users do
    resources :recipes
  end

  # get '/auth/facebook/callback', to: 'sessions#auth'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  validates :content, presence: true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe, optional: true
  validates :text, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: {case_sensitive: false}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :directions
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_one_attached :image

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :recipe_ingredients, presence: true
  validates :directions, presence: true

  accepts_nested_attributes_for :recipe_ingredients, reject_if: proc { |attr| attr[:quantity].blank? && attr[:ingredient_attributes][:name].blank? }, allow_destroy: true
  accepts_nested_attributes_for :directions, reject_if: proc { |attr| attr[:text].blank? }, allow_destroy: true

  scope :sorted, lambda {order("created_at DESC")}
  scope :search, lambda {|search| where(["name LIKE ?", "%#{search}%"])}

  def self.categories
    ['Breakfast', 'Lunch', 'Dinner', 'Dessert', 'Soup', 'Salad', 'Sauce', 'Appetizer', 'Side Dish']
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe, optional: true
  belongs_to :ingredient, optional: true

  def ingredient_attributes=(ingredient_attributes)
    ingredient_attributes.values.each do |attribute|
      if attribute != ''
        new_ingredient = Ingredient.find_or_create_by(name: attribute)
        self.ingredient = new_ingredient
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :has_recipe

  def create
    @comment = current_user.comments.create(comment_params)
    @comment.recipe = @recipe
    @comment.save
    render json: @comment, status: 201
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comments_params)
      flash[:success] = "Recipe successfully updated."
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    user = comment.user
    comment.destroy
    flash[:success] = "Recipe successfully deleted."
    redirect_to recipe_path(@recipe)
  end


  private

  def has_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
    render 'ingredients/_new_ingredient', :layout => false
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show,:edit,:update,:destroy]

  def index
    @recipes = Recipe.search(params[:search])
    @breakfast = Recipe.where("category = 'Breakfast'")
    @lunch = Recipe.where("category = 'Lunch'")
    @dinner = Recipe.where("category = 'Dinner'")
    @dessert = Recipe.where("category = 'Dessert'")
    @soup = Recipe.where("category = 'Soup'")
    @salad = Recipe.where("category = 'Salad'")
    @sauce = Recipe.where("category = 'Sauce'")
    @appetizer = Recipe.where("category = 'Appetizer'")
    @side = Recipe.where("category = 'Side Dish'")

    respond_to do |f|
      f.html
      f.json { render json: @recipes }
    end
  end

  def new
    if user_signed_in?
      @recipe = Recipe.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @recipe = Recipe.create(recipe_params)
    if @recipe.save
      flash[:success] = "Recipe successfully saved."

      respond_to do |f|
        f.html { redirect_to recipe_path(@recipe) }
        f.json { render json: @recipe }
      end
    else
      render :new
    end
  end

  def show
    if current_user
      @comment = current_user.comments.build(recipe: @recipe)
    end
    respond_to do |f|
      f.html { render :show}
      f.json { render json:  @recipe }
    end
  end

  def edit

  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
      flash[:success] = "Recipe successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    flash[:success] = "Recipe successfully deleted."
    redirect_to recipes_path
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(
      :name,
      :category,
      :prep_time,
      :cook_time,
      :user_id,
      :search,
      :image,
      directions_attributes: [:id, :text],
      recipe_ingredients_attributes: [
      :id,
      :quantity,
      ingredient_attributes: [:id, :name]])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @recipes = @user.recipes
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<%if flash[:notice] %>
<div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%=flash[:notice]%>
</div>
<%end%>

<%if flash[:alert] %>
    <div class="alert alert-dismissible alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
    </div>
<% end %>

<%if flash[:error]%>
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%=flash[:error]%>
    </div>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "My Recipe Box", '/', class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarNav">
  <% if user_signed_in? %>
    <ul class="nav navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "Recipes", recipes_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add A Recipe", new_user_recipe_path(current_user), class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.username.upcase %>
        </a>
      <div class="dropdown-menu bg-secondary" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to "My Profile", user_path(current_user), class:"user dropdown-item" %>
        <%= link_to "Edit Account", edit_user_registration_path, class: "dropdown-item" %>
        <%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", :method => :delete %>
      </div>
      </li>
      <%= form_tag(recipes_path, :method => "get", class: "form-inline my-2 my-lg-0", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Recipes", class: "form-control mr-sm-2" %>
        <span class="input-group-btn">
          <%= submit_tag "Search", class: "btn btn-outline-info my-2 my-sm-0" %>
        </span>
      <% end %>
    </ul>
  <% else %>
    <ul class="nav navbar-nav ml-auto">
      <li><%= link_to "Recipes", recipes_path, class: "nav-link" %></li>
      <li><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
      <li><%= link_to "Sign In", new_user_session_path, class: "nav-link" %></li>
      <%= form_tag(recipes_path, :method => "get", class: "form-inline my-2 my-lg-0", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Recipes", class: "form-control mr-sm-2" %>
        <span class="input-group-btn">
          <%= submit_tag "Search", class: "btn btn-outline-info my-2 my-sm-0" %>
        </span>
      <% end %>
    </ul>

  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Recipe Box</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
</head>
<body>
  <%= render "layouts/navbar" %>
  <%= render "layouts/flash" %>
  <div class="main">
    <div class="container-fluid">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/recipes/_direction_fields.html.erb
<div class="form-inline">
	<div class=" form-group nested-fields">
		<%= f.text_field(:text, class: "form-control", :placeholder => "Step (Ex: Fold in slowly)") %>
		<%= link_to_remove_association "X", f, class: "btn btn-danger" %>
	</div>
</div>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
<%= render 'shared/errors', object: f.object %>
<div class="row">
  <div class="col text-center" id="form-title">
    <h1>Add A New Recipe</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <h3>Recipe Info</h3>
  </div>
</div>
<div class="row" id="recipe-info">
  <div class="col-md-6">
    <%= f.text_field(:name, class: "form-control", :placeholder => "Name (Ex: Eggs Benedict)") %>
  </div>
  <div class="col-md-4 ml-auto">
    <%= f.select :category, options_for_select(Recipe.categories), :prompt => "Select a category" %>
  </div>
</div>
<div class="row" id="recipe-image">
  <div class="col">
    <h3>Recipe Image</h3>
    <%= f.file_field :image %>
  </div>
</div>
<div class="row">
  <div class="col">
    <h3>Time</h3>
  </div>
</div>
<div class="row" id="cook-prep-time">
  <div class="col">
    <div class="input-group mb-3 w-50">
      <%= f.text_field(:prep_time, class: "form-control", :placeholder => "Prep Time (Ex: 30)") %>
      <span class="input-group-text" id="basic-addon2">minute(s)</span><br>
    </div>
  </div>
  <div class="col">
    <div class="input-group mb-3 w-50">
      <%= f.text_field(:cook_time, class: "form-control", :placeholder => "Cook Time (Ex: 30)") %>
      <span class="input-group-text" id="basic-addon2">minute(s)</span><br>
    </div>
  </div>
</div>
<div class="row" id="ingredients-directions-fields">
  <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6">
    <h3>Ingredients</h3>
  <div id="recipe-ingredients">
    <%= f.fields_for(:recipe_ingredients) do |ri| %>
    <%= render 'recipe_ingredient_fields', f: ri  %>
    <% end %>
  </div>
    <%= link_to_add_association "Add Ingredient", f, :recipe_ingredients, class: "btn btn-secondary form-button", data:
    { association_insertion_node: '#recipe-ingredients', association_insertion_method: :before },
    :wrap_object => Proc.new {|ri| ri.build_ingredient; ri } %>
  </div>
  <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6">
    <h3>Directions</h3>
    <div id="directions">
      <%= f.fields_for(:directions) do |direction| %>
      <%= render 'direction_fields', f: direction %>
      <% end %>
    </div>
    <%= link_to_add_association "Add Step", f, :directions, class: "btn btn-secondary form-button", data:
    { association_insertion_node: '#directions', association_insertion_method: :before } %>
  </div>
</div>
<div class="row" id="submitted">
  <div class="col">
    <div class="actions">
      <%= f.hidden_field(:user_id, value: current_user.id) %>
      <%= f.submit class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>
  <div class="col">
    <%= link_to "Cancel", recipes_path, class: "btn btn-danger" %>
  </div>
</div>

app/views/recipes/_recipe_ingredient_fields.html.erb
<div class="form-inline">
  <div class="form-group nested-fields">
		<%= f.text_field(:quantity, class: "form-control w-40", :placeholder => "Quantity (Ex: 1 cup)") %>

		<%= f.fields_for(:ingredient) do |ri_ingredient| %>
		<%= ri_ingredient.text_field(:name, class: "form-control w-40", :placeholder => "Name (Ex: diced chicken)") %>
	  <% end %>
		<%= link_to_remove_association "X", f, class: "btn btn-danger" %>
	</div>
</div>

app/views/recipes/edit.html.erb
<h1>Edit Your Recipe</h1>

<%= render "form", recipe: @recipe, submit_btn: "Update" %>
<%= link_to "Cancel", user_path(@recipe.user), class: "btn btn-danger" %>

app/views/recipes/index.html.erb
<div class="text-center">
  <h2>Breakfast</h2>
</div>
<div class="row">
  <% @breakfast.each do |recipe| %>
  <div class="col-xs-12 col-sm-4">
<div class="card" style="width: 18rem;">
<%= image_tag recipe.image, class: "img-fluid img-thumbnail" %>
<div class="card-body">
<h5 class="card-title"><%= recipe.name.titleize %></h5>
<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
<%= link_to "View Recipe", recipe_path(recipe)%>
</div>
</div>
</div>
<% end %>
</div>

app/views/recipes/new.html.erb
<div class="form-group">
  <div class="panel-body">
    <%= render "form", recipe: @recipe, submit_btn: "Create Recipe" %>
  </div>
</div>

app/views/recipes/show.html.erb
  <div class="row">

      <div class="col">
        <h1>
          <%= @recipe.name.split.map(&:capitalize).join(' ') %>
        </h1>
        <h4> Recipe by: <%= link_to @recipe.user.username.capitalize, user_path(@recipe.user), id: "user" %></h4>
      </div>
      <div class="col">
        <h2>Category</h2>
          <p><%= @recipe.category %></p>
        <h2>Prep Time</h2>
          <p><%= @recipe.prep_time %> minute(s)</p>
        <h2>Cook Time</h2>
          <p><%= @recipe.cook_time %> minute(s)</p>
      </div>
      <div class="col">
        <%= image_tag @recipe.image, class: "img-thumbnail w-75" %>
      </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h2>Ingredients</h2>
      <ul id="ingredients-list">
        <% @recipe.recipe_ingredients.each do |ri| %>
          <li class="ingredients"><%= ri.quantity %> <%= ri.ingredient.name %> </li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-6">
      <h2>Directions</h2>
      <ul>
        <% @recipe.directions.each do |dir| %>
        <li id="directions" ><%= dir.text %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-12">
      <% if current_user %>
      <h4>Add a comment:</h4>
      <%= form_for @comment, url: recipe_comments_path(@recipe, @comment)  do |f| %>
      <%= f.text_area :content, class: 'commentBox form-control' %>
      <button type="submit" class="btn btn-sm btn-primary">Create Comment</button>
      <% end %><br>
      <% else %>
      <p>Please log in order to add a comment.</p>
      <% end %>
    </div>
    <div class="col-md-12">
      <div class="well-white">
        <h2>Comment(s)</h2>
        <hr>
        <div id="submitted-comments">
          <% @recipe.comments.each do |comment| %>
          <blockquote>
            <div class="well-white well-white" id="comment-<%= comment.id %>">
              <strong class="commentUserName"><%= comment.user.username %></strong> commented: <span class="commentContent"><%= comment.content %> </span>
              <% if current_user == @recipe.user || current_user == @comment.user %>
                <span><%= link_to '',recipe_comment_path(@recipe, comment), method: :delete,
                data: { confirm: 'Are you sure?' }, class: 'glyphicon glyphicon-trash' %></span>
              <% end %>
            </div>
          </blockquote>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <% if current_user == @recipe.user %>
  <%= link_to "Edit Recipe", edit_recipe_path, class: "btn btn-sm btn-info" %>
  <%= link_to "Delete Recipe", recipe_path, method: :delete, class: "btn btn-sm btn-danger" %>
  <% end %>
  <%= link_to "Recipes Home", recipes_path, class: "btn btn-sm btn-secondary" %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="form_error">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="form-field">
  <%= form_for(user) do |f| %>
    <%= render 'shared/errors', object: f.object %>
    <div>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>

    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.submit submit_btn, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render partial: "form", locals: {user: @user, submit_btn: "Update"} %>

app/views/users/home.html.erb
<div>
<h1>Recipe Manager</h1>

<h2>Manage Your Recipe Catalog Online</h2>
<p>
Life is much more complicated now than it was ever before. It seems we're
always on the go, and this can take a toll on our health. Why not make eating
at home a little easier to do? With this recipe manager, you can have all your
favorite recipes at your fingertips. Arrange recipes by complexity, time to
prepare, type of dish, and much more!
</p>

</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render partial: "form", locals: {user: @user, submit_btn: "Sign Up"} %>


<%
=begin
%>
<%= #link_to("Sign Up with Facebook", "/auth/facebook", class: "btn btn-default") %>
<%
=end
%>

app/views/users/show.html.erb
<h1>
  <%= @user.username.capitalize %>
  <div class="user-editor">
    <% if logged_in? && @user == current_user %>
      <%= link_to "Edit Your Profile", edit_user_path(@user), class: "btn btn-sm btn-primary" %>
      <%= link_to "Delete Your Account", user_path(@user), method: :delete, class: "btn btn-sm btn-default" %>
      <%= link_to "Add Recipe", new_user_recipe_path(@user), class: "btn btn-sm btn-primary" %>
    <% end %>
  </div>
</h1>

<h2>Recipes</h2>
<div class="recipes">
  <ul>
    <% @recipes.each do |recipe| %>
      <%=  link_to recipe.name, user_recipe_path(recipe), class:"recipe-name" %>
      <div class="recipe-editor">
        <% if logged_in? && recipe.user == current_user %>
          <%= link_to "Edit Recipe", edit_user_recipe_path(recipe), class: "btn btn-sm btn-primary" %>
          <%= link_to "Delete Recipe", recipe_path(recipe), method: :delete, class: "btn btn-sm btn-default" %>
        <% end %>
      </div>
    <% end %>
  </ul>
</div>